### ISSUE TITLE
DateTime related tests fail on a timezone out of Asia/Tokyo

### ISSUE THREAD

**Issue by miyakawataku** [cero-t/sqltemplate#20]
Test cases which use Date and Time API types fail on a machine out of Asia/Tokyo.

## How to reproduce the issue

On a timezone which is not Asia/Tokyo, such as UTC:

```
$ cat /etc/timezone
UTC
```

Run unit tests for bootiful-sqltemplate-core:

```
$ mvn test
```

## Expected result

All tests are expected to pass.

## Actual result

 8 tests around Date and Time failed.

```
testForObject_SingleDateTime(ninja.cero.sqltemplate.core.SqlTemplateTest)  Time elapsed: 0.025 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is "2001-01-26T12:34:59.789"
     but: was "2001-01-26T21:34:59.789"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at ninja.cero.sqltemplate.core.SqlTemplateTest.testForObject_SingleDateTime(SqlTemplateTest.java:563)

testForList_SingleDateTime(ninja.cero.sqltemplate.core.SqlTemplateTest)  Time elapsed: 0.006 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is "2001-01-26T12:34:59.789"
     but: was "2001-01-26T21:34:59.789"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at ninja.cero.sqltemplate.core.SqlTemplateTest.testForList_SingleDateTime(SqlTemplateTest.java:544)

testBatchUpdate_byEntity(ninja.cero.sqltemplate.core.SqlTemplateTest)  Time elapsed: 0.008 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is <2015-04-01>
     but: was <2015-03-31>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at ninja.cero.sqltemplate.core.SqlTemplateTest.testBatchUpdate_byEntity(SqlTemplateTest.java:823)

testForObject_DateTime(ninja.cero.sqltemplate.core.SqlTemplateTest)  Time elapsed: 0.012 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is "2001-01-23 12:34:56.789"
     but: was "2001-01-23 21:34:56.789"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at ninja.cero.sqltemplate.core.SqlTemplateTest.testForObject_DateTime(SqlTemplateTest.java:522)

testForListMap_DateTime(ninja.cero.sqltemplate.core.SqlTemplateTest)  Time elapsed: 0.012 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is "2001-01-26 12:34:59.789"
     but: was "2001-01-26 21:34:59.789"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at ninja.cero.sqltemplate.core.SqlTemplateTest.testForListMap_DateTime(SqlTemplateTest.java:584)

testUpdate_DateTime(ninja.cero.sqltemplate.core.SqlTemplateTest)  Time elapsed: 0.017 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is "2001-01-24"
     but: was "2001-01-23"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at ninja.cero.sqltemplate.core.SqlTemplateTest.testUpdate_DateTime(SqlTemplateTest.java:620)

testUpdate_insertByEntity(ninja.cero.sqltemplate.core.SqlTemplateTest)  Time elapsed: 0.006 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is <2015-04-01>
     but: was <2015-03-31>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at ninja.cero.sqltemplate.core.SqlTemplateTest.testUpdate_insertByEntity(SqlTemplateTest.java:401)

testUpdate_DateTime_ZoneAware(ninja.cero.sqltemplate.core.SqlTemplateTest)  Time elapsed: 0.013 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is "2001-01-24"
     but: was "2001-01-23"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at ninja.cero.sqltemplate.core.SqlTemplateTest.testUpdate_DateTime_ZoneAware(SqlTemplateTest.java:690)
```

**Comment by cero-t** [comment]
Fixed.
https://github.com/cero-t/sqltemplate/commit/dae865f29169a61585f9906cb8d159988d73280a
