### ISSUE TITLE
no defined "VERSION_2_3_30" in freemarker.template.Configuration

### ISSUE THREAD

**Issue by Minori-Akizuki** [cero-t/sqltemplate#25]
```
java.lang.NoSuchFieldError: VERSION_2_3_30
        at ninja.cero.sqltemplate.core.template.FreeMarker.<clinit>(FreeMarker.java:13) ~[bootiful-sqltemplate-2.0.0-M3.jar:na]
        at ninja.cero.sqltemplate.core.template.TemplateEngine.<clinit>(TemplateEngine.java:26) ~[bootiful-sqltemplate-2.0.0-M3.jar:na]
        at ninja.cero.sqltemplate.SqlTemplate.file(SqlTemplate.java:43) ~[bootiful-sqltemplate-2.0.0-M3.jar:na]
```

FreeMarkerバージョン指定の為の変数だと思うのですが、使用しようとしているバージョンのための定数が定義されていないためSQLを発行しようとすると落ちてしまいます。
おそらく定数の追加をすれば直ると思います。

**Comment by Minori-Akizuki** [comment]
このライブラリの問題じゃないですね。FreeMarkerの問題ですねこれ……失礼しました。
手元のPOMでFileMarkerのバージョンを2.3.31にしたらエラーが出なくなりました。
ライブラリのPOM見る限りFileMarkaerのバージョンは2.3.30の様なのでなぜこうなるのかは謎ですが……

**Comment by cero-t** [comment]
コメント気づいてませんでした、すみません！
そんな問題あったんですね、、ありがとうございます。
諸々、バージョンを見直します。

**Comment by cero-t** [comment]
私の環境では問題を再現できていないのですが、
ひとまずFreeMarkerを2.3.31にアップデートしたので、次のリリースで問題が起きなくなるはずです。
https://github.com/cero-t/sqltemplate/commit/30d4a2c3f0071dce5e204ace7a087a154aeb0120
